# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-02 14:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Code',
            fields=[
                ('code_name', models.CharField(max_length=12, primary_key=True, serialize=False, verbose_name='Code File Name')),
                ('create_date', models.DateTimeField(verbose_name='Date Created')),
                ('last_save_date', models.DateTimeField(blank=True, null=True, verbose_name='Date Last Saved')),
                ('share_url', models.CharField(blank=True, max_length=12, null=True, verbose_name='Share URL')),
                ('code_lang', models.CharField(blank=True, max_length=10, null=True, verbose_name='Code Language')),
                ('shared', models.BooleanField(default=False, verbose_name='Is Shared')),
            ],
        ),
    ]
