# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-23 10:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='code',
            name='id',
        ),
        migrations.AlterField(
            model_name='code',
            name='code_name',
            field=models.CharField(max_length=12, primary_key=True, serialize=False),
        ),
    ]
