# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-23 10:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0002_auto_20160423_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='code',
            name='code_lang',
            field=models.CharField(max_length=10, verbose_name='Code Language'),
        ),
        migrations.AlterField(
            model_name='code',
            name='code_name',
            field=models.CharField(max_length=12, primary_key=True, serialize=False, verbose_name='Code File Name'),
        ),
        migrations.AlterField(
            model_name='code',
            name='create_date',
            field=models.DateTimeField(verbose_name='Date Created'),
        ),
        migrations.AlterField(
            model_name='code',
            name='last_save_date',
            field=models.DateTimeField(verbose_name='Date published'),
        ),
        migrations.AlterField(
            model_name='code',
            name='share_url',
            field=models.CharField(max_length=12, verbose_name='Share URL'),
        ),
    ]
