# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-23 10:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0003_auto_20160423_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='code',
            name='last_save_date',
            field=models.DateTimeField(verbose_name='Date Last Saved '),
        ),
    ]
