# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-23 10:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0004_auto_20160423_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='code',
            name='code_lang',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Code Language'),
        ),
        migrations.AlterField(
            model_name='code',
            name='last_save_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date Last Saved'),
        ),
        migrations.AlterField(
            model_name='code',
            name='share_url',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='Share URL'),
        ),
    ]
