# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-23 08:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Code',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(verbose_name=b'date published')),
                ('last_save_date', models.DateTimeField(verbose_name=b'date published')),
                ('share_url', models.CharField(max_length=12)),
                ('code_name', models.CharField(max_length=12)),
                ('code_lang', models.CharField(max_length=10)),
            ],
        ),
    ]
